# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "settip up...."
      - shell: bash
        run: 
           echo "for testing of artifact" > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
           name: output-log-file
           path: output.log
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
             name: output-log-file
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building...."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo  "testing......."
